# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ECTutorKit' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ECTutorKit
  pod 'MBProgressHUD', '1.0.0'
  # pod 'UIImage+PDF', '1.1.3'
  pod 'GoogleAnalytics'

  target 'ECTutorKitTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
